---
- name: checkout Nim repo
  git: repo=https://github.com/nim-lang/Nim.git dest=/opt/Nim

- name: checkout csources
  git: repo=https://github.com/nim-lang/csources dest=/opt/Nim/csources

- name: build csources
  shell: cd /opt/Nim/csources && sh build.sh

- name: build koch
  shell: cd /opt/Nim && bin/nim c koch

- name: build nim
  shell: cd /opt/Nim && ./koch boot -d:release

- name: make a link to Nim binary
  file: state=link src=/opt/Nim/bin/nim dest=/usr/bin/nim
